// app/api/quiz/[quizId]/duplicate/route.ts
// POST — deep-copy an existing quiz/survey into a fresh editable draft.
//
// The clone belongs to the current user, starts UNPUBLISHED with every
// counter reset to 0, and carries over the whole editable config
// (design, capture settings, questions, result profiles). Leads /
// responses / stats are deliberately NOT copied. Free-plan creation
// limits are enforced the same way as POST /api/quiz so a duplicate can
// never bypass the per-mode cap.
import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServerClient } from "@/lib/supabaseServer";
import { isPaidPlan, FREE_LIMITS } from "@/lib/planLimits";
import { resolveProjectIdForInsert } from "@/lib/projects/scopeFilter";
import { sanitizeSlug } from "@/lib/quizBranding";

export const dynamic = "force-dynamic";

type RouteContext = { params: Promise<{ quizId: string }> };

// Columns that must NEVER be copied verbatim onto the clone. Identity /
// timestamps are regenerated by Postgres defaults; counters + status +
// slug + title are overridden explicitly below; embed_session_id belongs
// to the anonymous embed flow and has a partial-unique index, so a real
// user-owned clone must leave it NULL.
const NON_COPYABLE_QUIZ_COLUMNS = new Set([
  "id",
  "created_at",
  "updated_at",
  "embed_session_id",
  "views_count",
  "starts_count",
  "completions_count",
  "shares_count",
  "status",
  "title",
  "slug",
  "user_id",
  "project_id",
  // L'analyse IA parle des chiffres de l'ORIGINAL (drame Jocelyne, 4 aout
  // 2026). Copiee telle quelle, elle s'affiche sur une copie a zero vue en
  // commentant "113 vues, 55 demarrages", avec la date de l'original. La
  // copie n'a aucune donnee : elle ne doit donc afficher aucune analyse.
  "ai_insights",
  "ai_insights_at",
]);

// Per-child columns regenerated on insert (id + FK + timestamps).
const NON_COPYABLE_CHILD_COLUMNS = new Set([
  "id",
  "quiz_id",
  "created_at",
  "updated_at",
]);

function stripColumns(
  row: Record<string, unknown>,
  drop: Set<string>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(row)) {
    if (!drop.has(k)) out[k] = v;
  }
  return out;
}

/**
 * Build a fresh, collision-free slug for the clone. A draft copy uses its
 * own UUID URL when the source had no custom slug (slug = null). When the
 * source DID have a custom slug we derive `<slug>-copie` (then -copie-2,
 * -copie-3…) and fall back to null if we can't find a free variant.
 */
async function buildCloneSlug(
  supabase: Awaited<ReturnType<typeof getSupabaseServerClient>>,
  sourceSlug: unknown,
): Promise<string | null> {
  const base = sanitizeSlug(sourceSlug);
  if (!base) return null;

  for (let attempt = 0; attempt < 20; attempt++) {
    const suffix = attempt === 0 ? "-copie" : `-copie-${attempt + 1}`;
    const candidate = sanitizeSlug(base + suffix);
    if (!candidate) break;
    const { data: conflict } = await supabase
      .from("quizzes")
      .select("id")
      .ilike("slug", candidate)
      .limit(1)
      .maybeSingle();
    if (!conflict) return candidate;
  }
  return null;
}

export async function POST(_req: NextRequest, context: RouteContext) {
  try {
    const { quizId } = await context.params;
    const supabase = await getSupabaseServerClient();
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) {
      return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }

    // Ownership check: the source must belong to the current user.
    const { data: source, error: sourceError } = await supabase
      .from("quizzes")
      .select("*")
      .eq("id", quizId)
      .eq("user_id", user.id)
      .maybeSingle();
    if (sourceError) {
      return NextResponse.json({ ok: false, error: sourceError.message }, { status: 400 });
    }
    if (!source) {
      return NextResponse.json({ ok: false, error: "Quiz not found" }, { status: 404 });
    }

    const sourceRow = source as Record<string, unknown>;
    const mode =
      sourceRow.mode === "survey"
        ? "survey"
        : sourceRow.mode === "scoring"
          ? "scoring"
          : "quiz";
    const isSurvey = mode === "survey";

    // Free-plan creation gate — identical to POST /api/quiz. A duplicate
    // adds one more item of this mode, so a free creator already at the
    // cap (their single quiz/survey) is refused here too.
    const { data: profile } = await supabase
      .from("profiles")
      .select("plan")
      .eq("user_id", user.id)
      .maybeSingle();

    if (!isPaidPlan((profile as { plan?: string | null } | null)?.plan)) {
      const { count } = await supabase
        .from("quizzes")
        .select("id", { count: "exact", head: true })
        .eq("user_id", user.id)
        .eq("mode", mode);

      if ((count ?? 0) >= FREE_LIMITS.maxQuizzesPerMode) {
        const errorCode = isSurvey ? "FREE_PLAN_SURVEY_LIMIT" : "FREE_PLAN_QUIZ_LIMIT";
        const message = isSurvey
          ? "Le plan gratuit est limité à 1 sondage. Passe en plan payant pour en créer plus."
          : "Le plan gratuit est limité à 1 quiz. Passe en plan payant pour en créer plus.";
        return NextResponse.json(
          { ok: false, error: errorCode, message },
          { status: 403 },
        );
      }
    }

    // Load the source children before inserting the clone so a read
    // failure aborts cleanly (nothing created yet).
    const [questionsRes, resultsRes] = await Promise.all([
      supabase.from("quiz_questions").select("*").eq("quiz_id", quizId).order("sort_order"),
      supabase.from("quiz_results").select("*").eq("quiz_id", quizId).order("sort_order"),
    ]);
    if (questionsRes.error) {
      return NextResponse.json({ ok: false, error: questionsRes.error.message }, { status: 400 });
    }
    if (resultsRes.error) {
      return NextResponse.json({ ok: false, error: resultsRes.error.message }, { status: 400 });
    }

    const projectId = await resolveProjectIdForInsert(user.id);
    const cloneSlug = await buildCloneSlug(supabase, sourceRow.slug);

    // Copy every editable column, then override identity / ownership /
    // status / counters. Counters are inserted at 0 here (a brand-new
    // row) — this never touches the source quiz's *_count columns.
    const newQuizRow: Record<string, unknown> = {
      ...stripColumns(sourceRow, NON_COPYABLE_QUIZ_COLUMNS),
      user_id: user.id,
      project_id: projectId,
      slug: cloneSlug,
      title: `${String(sourceRow.title ?? "")} (copie)`,
      status: "draft",
      views_count: 0,
      starts_count: 0,
      completions_count: 0,
      shares_count: 0,
    };

    const { data: inserted, error: insertError } = await supabase
      .from("quizzes")
      .insert(newQuizRow)
      .select("id, slug")
      .single();
    if (insertError || !inserted) {
      return NextResponse.json(
        { ok: false, error: insertError?.message ?? "Failed to duplicate quiz" },
        { status: 400 },
      );
    }

    const newQuizId = (inserted as { id: string }).id;

    // Copy questions (new ids, same order/content).
    const questions = (questionsRes.data ?? []) as Record<string, unknown>[];
    if (questions.length > 0) {
      const { error: qErr } = await supabase.from("quiz_questions").insert(
        questions.map((q) => ({
          ...stripColumns(q, NON_COPYABLE_CHILD_COLUMNS),
          quiz_id: newQuizId,
        })),
      );
      if (qErr) {
        // Best-effort cleanup: cascade delete removes the partial clone.
        await supabase.from("quizzes").delete().eq("id", newQuizId);
        return NextResponse.json(
          { ok: false, error: `Échec de la copie des questions : ${qErr.message}` },
          { status: 400 },
        );
      }
    }

    // Copy result profiles (new ids, same content) so scoring/profils are
    // preserved. Surveys carry zero results — the loop simply no-ops.
    const results = (resultsRes.data ?? []) as Record<string, unknown>[];
    if (results.length > 0) {
      const { error: rErr } = await supabase.from("quiz_results").insert(
        results.map((r) => ({
          ...stripColumns(r, NON_COPYABLE_CHILD_COLUMNS),
          quiz_id: newQuizId,
        })),
      );
      if (rErr) {
        await supabase.from("quizzes").delete().eq("id", newQuizId);
        return NextResponse.json(
          { ok: false, error: `Échec de la copie des résultats : ${rErr.message}` },
          { status: 400 },
        );
      }
    }

    return NextResponse.json({
      ok: true,
      id: newQuizId,
      slug: (inserted as { slug: string | null }).slug ?? null,
    });
  } catch (e) {
    return NextResponse.json(
      { ok: false, error: e instanceof Error ? e.message : "Unknown error" },
      { status: 500 },
    );
  }
}
